language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist
